services:
  - type: web
    name: line-rain-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        value: ใส่_ACCESS_TOKEN_ของคุณที่นี่
      - key: LINE_CHANNEL_SECRET
        value: ใส่_CHANNEL_SECRET_ของคุณที่นี่
      - key: OPENWEATHER_API_KEY
        value: ใส่_API_KEY_ของคุณที่นี่
